# Hardware configuration for the 'pc' host (generated by NixOS).
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ config, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];

    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/0c640fd3-06d4-4f0a-ae40-1e3196eeabe4";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/DBC2-DE8D";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    "/mnt/data" = {
      device = "/dev/disk/by-uuid/5fba3e91-8a75-46c5-b123-d54856b98a7d";
      fsType = "ext4";
    };

    "/mnt/archive" = {
      device = "/dev/disk/by-uuid/a489818a-e745-4bbe-8af8-d0c7f103bf52";
      fsType = "ext4";
    };
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/032ff3fb-7d74-466e-94f5-c83ebdaa5333"; } ];

  # NetworkManager handles networking
  nixpkgs.hostPlatform = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;
}
