{
  imports = [
    ./alacritty.nix
    ./cli/bat.nix
    ./cli/cava.nix
    ./cli/eza.nix
    ./git.nix
    ./cli/htop.nix
    ./hyprland
    ./cli/lazygit.nix
    ./mime.nix
    ./obsidian.nix
    ./qt.nix
    ./stylix.nix
    ./swaync
    ./music/spicetify.nix
    ./waybar
    ./wofi
    ./zsh
    ./cli/zathura.nix
    ./cli/zoxide.nix
  ];
}
